name: g36_conformance_test

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: sleep infinity
    volumes:
      - ./:/work
      - cache:/root/.cache
      - cache:/root/.openmodelica
    ports:
      - "8501:8501"  # streamlit UI served by `g36conftest-viz`
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t


volumes:
  cache:
