name: g36_conformance_test

services:
  simulation:
    build:
      context: .
      dockerfile: docker/Dockerfile.simulation
    volumes:
      - ./:/mnt/shared
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t

  bacnet:
    build:
      context: .
      dockerfile: docker/Dockerfile.bacnet