[project]
name = "g36conftest"
version = "0.0.1"
# 'common'
dependencies = [ 
    "pyyaml",
    "pandas",
    "numpy",
    "openpyxl",
    'pint',
]

[project.optional-dependencies] # (not dep group)
# installable like g36conftest[bacnet, simulation]
# interpreted as 'features' by pixi
bacnet =     ["BAC0"]
simulation = ["pyfmi", ] # pyfmi on pypi is neglected:
# last update dec ~2018.
# no windows wheel.
# otherwise this is almost a std standard python project.
[tool.pixi.feature.simulation.dependencies]
pyfmi = '*'  # get pyfmi from conda (overrides above)
[tool.pixi.feature.simulation.target.linux-64.dependencies]
omcompiler = '*'                                            # openmodelica only available on linux64
[tool.pixi.feature.simulation.target.win-64.dependencies]   # but not other platforms (install it some other way)
[tool.pixi.feature.simulation.target.win-64.activation]
env = {"PATH" = "%PATH%;%OPENMODELICAHOME%/bin" }
[tool.pixi.feature.simulation.target.osx-64.dependencies]    # so these are empty to denote not to do anything
[tool.pixi.feature.simulation.target.osx-arm64.dependencies] # so these are empty to denote not to do anything
[tool.pixi.feature.simulation.target.linux-aarch64.dependencies] # so these are empty to denote not to do anything


[project.scripts]
g36conftest = "g36conftest.cli:cli"


[dependency-groups]
test = ["pytest",]# 'pytest-regressions']
#'dev' specifically can be for debugging, formatting,
dev = [ {include-group = "test"}, ] # 


[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = [
    "win-64", "linux-64", "osx-64",
    "osx-arm64", "linux-aarch64"]

[tool.pixi.pypi-dependencies]
g36conftest = { path = ".", editable = true }


[tool.pixi.environments]
default = { solve-group = "default" }  # just the 'common' ones
bacnet =    {  features = ["bacnet",     'test'],   solve-group = "default" }
simulation = { features = ["simulation", 'test'],   solve-group = "default" }

[tool.pixi.tasks]

